### PR TITLE
Add a little of design.

### PR DESCRIPTION
**Pull request by BeardedBear**

### CODE REVIEW

**Comment by BeardedBear** [comment]
If you accept my help, could I set up a simple scss/css compilation system, like parcel? ^^

**Comment by magopian** [comment]
Wow thanks a lot for your help. I'm a bit confused, I should have explained that I'd rather have a single file, as minimalistic as possible, without any dependencies or external ressources (no fonts, no css, no js...).
The rationale is that it's way easier to manage, it's also way more accessible to low bandwidth, and way lighter on the server.
Also, it's a very simple form, I'm not sure we need anything fancy ;)

**Comment by creaforge** [comment]
No worries Mathieu :) I was working on it this morning out of boredom, without any expectations. I understand that this is a lot of unsolicited changes.
Also, I totally agree with you on keeping the payload minimal, especially if the popularity of your website blows up!

Cheers

**Comment by magopian** [comment]
Closed in favor of #3, but snatched some of the CSS from here, thanks again @BeardedBear  !

**Pull request closed without merging**
